[package]
name = "game_lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.14.0"
smol = "2.0.0"
strum = { version = "0.26.1", features = ["derive"] }
strum_macros = "0.26.1"
